### ISSUE TITLE
JS 에서 상속과 결합에 관한 이슈

### ISSUE THREAD

**Issue by hansangho** [ncuiteam/codereview#1]
https://github.com/ncuiteam/codereview/blob/0b9a800cc293129030a9692a3377deafb7eeeede/2017/0822-bnsEsports2017-js/js/AbsSection.js

리뷰 시간에 얘기 나왔던 상속과 결합 관련한 이야기 인데요
실무중에 명확한 관계가 설정되기 힘든 경우가 많긴 하지만 
제경우는 보통 is-a 인 경우 상속을 사용하고 has-a 인 경우 결합을 사용한다는 원칙을 기반으로 코드 작성을 하려고 하는 편입니다.

AbsSection.js 샘플 코드의 경우 "자식 클래스의 인스턴스"는 "섹션"이다 라는 is-a 관계가 성립되고 있습니다.
개인적인 경험상 위의 결합 상속 원칙에 의해 코드 작성시 운영이나 의존성 이슈가 발생한 경험은 많지 않은데요

다른 의견 가지신 분들( @ingpdw )의 의견을 부탁 드립니다~~ ^^

**Comment by ingpdw** [comment]
안녕하세요~ 이견이 없습니다. ㅋㅋㅋ
저도 is-a인 경우 상속을 활용하고 있어요~

어제 결합 얘기가 나온 것은 프로젝트에서 사용되는 각각의 클래스의 의존성을 제거하고
클래스 간 의존성, 데이터 처리, 로직 제어를 mediator class에서 처리하니깐 운영할 때
이점이 많더라 라는 얘기를 드린 거였습니다. ^^
중재자 패턴은 내일 같이 또 보시죠~


2017년 8월 23일 오전 9:42, hansangho <notifications@github.com>님이 작성:

**Comment by ncuiteam** [comment]
굳 좋은 의견 감사합니다~~
